/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jéssica Magno (https://sketchfab.com/jessica_magno)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-minecraft-3c7b1e0e9a5f4897805b7ec3c4eeb5a5
Title: Fox minecraft
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'

import scene from '../assets/3d/fox.glb'

const Fox = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());

    if(actions[currentAnimation]) {
      actions[currentAnimation].play();
    }
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0, 0, 0.006]}
          rotation={[-1.566, 0, 0.01]}
          scale={0.135}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Head_0" position={[-8.42, 0.988, 0.022]} scale={[2.974, 2.974, 3.965]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials.Material}
                />
                <mesh
                  name="Object_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_5.geometry}
                  material={materials['Material.001']}
                />
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Mice_1" position={[-12.773, -0.996, 0.02]} scale={[1.402, 0.989, 1.982]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.Material}
                />
                <mesh
                  name="Object_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_9.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="UHO_2" position={[-9.935, 4.945, -2.957]} scale={[0.496, 0.992, 0.992]}>
                <mesh
                  name="Object_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_11.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="UHO2_3"
                position={[-9.914, 4.945, 3.015]}
                rotation={[0, 0, Math.PI]}
                scale={[-0.496, -0.992, -0.992]}>
                <mesh
                  name="Object_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_13.geometry}
                  material={materials.Material}
                />
              </group>
              <group name="Fox_4" scale={[5.452, 2.974, 2.974]}>
                <mesh
                  name="Object_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_15.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="Hvost_5"
                position={[5.397, -0.112, -0.071]}
                scale={[4.447, 1.976, 1.976]}>
                <mesh
                  name="Object_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_17.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="LegL2_6"
                position={[3.142, -2.323, 2.271]}
                rotation={[0, 0, Math.PI / 6]}
                scale={[1.018, 2.848, 0.949]}>
                <mesh
                  name="Object_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_19.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="LegR2_7"
                position={[3.436, -2.323, -2.122]}
                rotation={[0, 0, 2.618]}
                scale={[-1.018, -2.848, -0.949]}>
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="LegL1_8"
                position={[-3.813, -2.323, 2.115]}
                rotation={[0, 0, -Math.PI / 6]}
                scale={[1.018, 2.848, 0.949]}>
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials.Material}
                />
              </group>
              <group
                name="LegR1_9"
                position={[-3.621, -2.323, -2.034]}
                rotation={[0, 0, -2.618]}
                scale={[-1.018, -2.848, -0.949]}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.Material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Fox;
